# Generated by Django 5.1.1 on 2024-11-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_delete_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default=0.0, max_length=255),
        ),
        migrations.AddField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(default=0.0, max_length=255),
        ),
    ]
